version: '3.1'

services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${TESTDATA}:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
